### ISSUE TITLE
Some blog titles still have html entities

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#105]
Found one with tittle:

Introducing `Nemo&#58;`HPE Nimble Storage Advanced Data Services Emulator for Containers

**Comment by reddypramod85** [comment]
I have added a fix before and I don't see the issue now. Where did you see the issue?
![image](https://user-images.githubusercontent.com/12749370/102360086-3226e500-3f77-11eb-9b8d-9d4b2b0e1ce3.png)

**Comment by Didier-Lalli** [comment]
I see it in the current version 

![image](https://user-images.githubusercontent.com/11722750/102459602-1b9b8f00-4046-11eb-8668-022ca2e5d16f.png)

But not in your latest branch.

**Comment by reddypramod85** [comment]
fixed.
