### ISSUE TITLE
Formatting of blogs

### ISSUE THREAD

**Issue by drensing** [hpe-dev-incubator/hpe-dev-portal#121]
Reviewed the new blog site and noticed that the body text takes up only half the screen and the title on the left takes up the other half. In design terms (HPE Brand), my understanding is that a page is made up of 3 columns and that the text should take up 2 columns with the left sidebar only taking up 1 column maximum. If the text takes up only half, the reader will  need to scroll down too far to read everything and there will be a lot of wasted space on the left.

**Comment by reddypramod85** [comment]
@drensing The formatting should be good now. Please check and let me know.
