### ISSUE TITLE
Create a Newsletter Page with Archive list

### ISSUE THREAD

**Issue by reddypramod85** [hpe-dev-incubator/hpe-dev-portal#125]
![image](https://user-images.githubusercontent.com/12749370/105136560-74cc6780-5ab7-11eb-9654-97f9a4636539.png)

**Comment by choukden** [comment]
Designed merged the archive page in the Newsletter signup page so we have this issue.

we have two options here to fix

1)	Redirect https://developer.hpe.com/newsletter-archive to https://developer.hpe.com/newsletter-signup ( No development effort required)
2)	Create a newsletter-archive page https://developer.hpe.com/newsletter-archive ( I can create)

**Comment by reddypramod85** [comment]
created newsletter-archive page https://hpe-dev-portal.netlify.app/newsletter-archive/

**Comment by choukden** [comment]
@reddypramod85 
Thank you very much for the creation of the newsletter archive page. 

One remark:
If I go to the Newsletter archive page, https://hpe-dev-portal.netlify.app/newsletter-archive/ 
I do see the archives in chronological order (2018, 2019, 2020, 2021)

Now If I go to the Newsletter signup page, I do see archive section in reverse order (2021, 2020, 2019, 2018) which is good.

For consistency, is it possible to set the reverse chronological order for the Newsletter Archive page?

Thanks again
Denis

**Comment by reddypramod85** [comment]
@choukden I know you will catch that issue :) I already made the changes and will release it in the next PR.

**Comment by choukden** [comment]
@reddypramod85 

;-)
