### ISSUE TITLE
Markdown rendering doesn't show very nice tables

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#1366]
The markdown below works well in Github:

Name | Description | Github Repo
-- | -- | --
AgStack | AgStack consists of an open repository to create and publish   models, free and easy access to public data, interoperable frameworks for   cross-project use and topic-specific extensions and toolboxes. It will   leverage existing technologies such as agriculture standards (AgGateway,   UN-FAO, CAFA, USDA and NASA-AR); public data (Landsat, Sentinel, NOAA and   Soilgrids; models (UC-ANR IPM), and open source projects like Hyperledger,   Kubernetes, Open Horizon, Postgres, Django and more | https://github.com/agstack
Apache Logging (log4j) | Apache Log4j is a Java-based logging utility originally   written by Ceki Gülcü. It is part of the Apache Logging Services, a project   of the Apache Software Foundation. | https://github.com/apache/logging-log4j2

But looks very ugly on our web site:

![image](https://user-images.githubusercontent.com/11722750/190114254-54586f1e-7e78-4c6b-8541-f621e731b701.png)

**Comment by Didier-Lalli** [comment]
@reddypramod85 let me know if we can do anything as my I want to contribute to OSS page is ready to be published.

**Comment by reddypramod85** [comment]
@Didier-Lalli 

Can you please add this style tag in the markdown file and check if it improves the table structure?

<style>
table {
    display: block;
    width: 100%;
    width: max-content;
    max-width: 100%;
    overflow: auto; 
     -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none; 
    border:1px solid grey;
}
td {
   -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    border:1px solid grey;
    text-align: left !important; 
    padding: 10px !important;
}
thead tr:first-child td {
  -webkit-box-shadow: none;
  -moz-box-shadow: none;
  box-shadow: none;
  border:1px solid grey;
  text-align: center !important; 
  padding: 20px !important; 
  font-weight: bold !important;
}
</style>

**Comment by Didier-Lalli** [comment]
Works perfectly. I will add this to the contributor guide. 
Thanks
