### ISSUE TITLE
Searching blog leads to 404

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#141]
Seems like the URL should not have a /search/ section.

https://hpe-dev-portal.netlify.app/search/blog/making-ai-a-reality

**Comment by choukden** [comment]
same for platform search
A search in portal V2 redirect users to a wrong from https://hpe-dev-portal.netlify.app/**search**/platform/hpe-ezmeral-container-platform/home

The appropriate URL should be:

https://hpe-dev-portal.netlify.app/platform/hpe-ezmeral-container-platform/home

**Comment by reddypramod85** [comment]
@Didier-Lalli @choukden I provided a fix, please test and let me know.

**Comment by choukden** [comment]
@reddypramod85 
Looks good to me!

Thank you Pramod.
cc: @Didier-Lalli

**Comment by reddypramod85** [comment]
Closing the issue @Didier-Lalli @choukden
