### ISSUE TITLE
Preview send to bad URL

### ISSUE THREAD

**Issue by patrickfrancoisp** [hpe-dev-incubator/hpe-dev-portal#170]
During edition the preview send to a false URL

Target:
https://deploy-preview-169--hpe-dev-portal.netlify.app/content/platform/spiffe-and-spire-projects/spiffe-and-spire-projects-home

Modification (remove Bold)
https://deploy-preview-169--hpe-dev-portal.netlify.app/**content/**platform/spiffe-and-spire-projects/**spiffe-and-spire-projects-**home

Good:
https://deploy-preview-169--hpe-dev-portal.netlify.app/platform/spiffe-and-spire-projects/home

**Comment by reddypramod85** [comment]
@patrickfrancoisp I provided a fix and closing the issue. Please check and let me know if you still see the issue.
