### ISSUE TITLE
Management of PDF document as an asset in the CMS?

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#172]
For GreenLake platform page, we currently have a link to a CMS v1 PDF document asset (a Technical white paper).
(asset: /uploads/media/2020/6/gl4pc_eshop_bp_v1_35-1593186155592.pdf)
Link URL: https://developer.hpe.com/uploads/media/2020/6/gl4pc_eshop_bp_v1_35-1593186155592.pdf

How do we manage such type of asset in CMS v2?

**Comment by reddypramod85** [comment]
We will maintain the S3 bucket even during V2. So this PDF will exist.
