### ISSUE TITLE
Platform page priority not honoured on platforms 

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#177]
Seems like the page doesn't respect the values set to Priority and continue to display cards in alphabetical order.

**Comment by reddypramod85** [comment]
I added sort by priority on the platforms page.

**Comment by reddypramod85** [comment]
@Didier-Lalli can you please confirm and close?

**Comment by reddypramod85** [comment]
Fixed. Please open an issue again if you still see an issue.
