### ISSUE TITLE
Indirect blog links don't work in tags page and in blog page

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#1880]
They send to the stub article not to the target They really only work well in platform (opensource, Products, GreenLake) pages.

Clicking in a blog link card under tags page or in "related blogs" at the bottom of a blog page will direct you to the stub article.
For example, go to the blog post https://developer.hpe.com/blog/chapel-scales-new-heights-with-1-28-0/, check the "related blogs" section at the bottom of the post, click on blog link card "announcing Chapel 1.30.0".

**Comment by choukden** [comment]
For example, from the HPE Dev portal, go to https://developer.hpe.com/blog/tag/chapel
You will see a list of blog cards/tiles. SOme of the blog tile are what we call "blog link" that connect the reader back to external blog post published outside the HPE Dev community portal. 

For example:
 - NETCDF in Chapel Part1 (or Part2). 
 - Announcing Chapel 1.30.0!
 - Announcing Chapel 1.29.0!
 
If you click either of these blog link card, you will not be directed to the expected external blog post. You will be directed to the stub article (that is, the content of the blog link card as you can see it in the CMS editor of the blog link card).

Same observation for the blog link card "Intro to Core API: Part 1 (Integer Incrementing)" with tag "determine-ai".
