### ISSUE TITLE
Related blogs doesn't take disable flag into account

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#1934]

**Comment by choukden** [comment]
As an example, the blog post has been disabled "New PowerShell library for the HPE GreenLake platform" (Author: Lionel Jullien): https://hpe-dev-portal.netlify.app/admin/#/collections/blog/entries/new-powershell-library-for-the-hpe-greenlake-cloud-platform

This blog post has also a set of tags associated with it.
For example, **GreenLake**, **GLCP**,

If you go to the page https://developer.hpe.com/blog/tag/glcp or https://developer.hpe.com/blog/tag/greenlake you will see the blog card/tile for the blog post "New PowerShell library for the HPE GreenLake platform". 
Expectation is that once a post is disabled, the post card/tile associated with the post does no longer appear.

One workround is to delete all the tags associated with the blog post.
