### ISSUE TITLE
HPE Ezmeral platform name change - Can you change the name to HPE Ezmeral Software in the Blog menu "Products".

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#1962]
When you have time to look at this issue:

I recently changed the title of the platform “HPE Ezmeral” into “HPE Ezmeral Software” (Products category). The URL is still the same as before the title change: https://developer.hpe.com/platform/hpe-ezmeral/home/ This is not an issue. If the new name changed automatically in the top menu bar (Products), I noticed that it was not the case in the Blogs category.  Under the Blog menu “Products”, the platform name is still “HPE Ezmeral”. Is it possible to change it to “HPE Ezmeral Software”? I believe a manual change through code is needed here, whenever we change the title of a platform page.

Thanks,
Denis

**Comment by Didier-Lalli** [comment]
Fixed by PR#1994
