### ISSUE TITLE
Adding "HPE Swarm Learning" product to the Blog menu under "Products" category 

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#1963]
A new platform page has been added a few months ago: HPE Swarm Learning (https://developer.hpe.com/platform/swarm-learning/home/). I noticed that the new platform was not listed in the blog category under “Products”. Is it possible to add the product landing page “HPE Swarm Learning” to the blog category “Products”.

I have just published the first blog post linked to the product page “HPE Swarm Learning”. Blog post: https://developer.hpe.com/blog/announcing-hpe-swarm-learning-2-0-0/. I noticed that the blog post does not appear in the blog catalog “All”. It only appears in the blog category “Others”. I think the issue arises directly from the issue above. I think once the issue above is resolved, this issue will be resolved.

Thanks,
Denis

**Comment by Didier-Lalli** [comment]
Fixed by PR#2005
