### ISSUE TITLE
June 2023 Newsletter archive abstract seems a little odd

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#1966]
The abstract for the Newsletter June 2023 in the Newsletter Archive page is not correct.
Could you please have a look at the abstract and adjust to the abstract of the June Newsletter.

"Abstract" for the Newsletter archive tile from Dale:

_It’s June and you know what that means – HPE Discover! Hear what’s happening in the Hack Shack in this month’s newsletter and check out the new Workshops-on-Demand that will be previewed there._

Denis

**Comment by pramodreddysareddy** [comment]
Updated and pushed the changes to production.

Thanks,
Pramod

From: choukden ***@***.***>
Date: Monday, June 19, 2023 at 5:33 AM
To: hpe-dev-incubator/hpe-dev-portal ***@***.***>
Cc: Sareddy, pramod reddy ***@***.***>, Assign ***@***.***>
Subject: [hpe-dev-incubator/hpe-dev-portal] June 2023 Newsletter archive abstract seems a little odd (Issue #1966)

The abstract for the Newsletter June 2023 in the Newsletter Archive page is not correct.
Could you please have a look at the abstract and adjust to the abstract of the June Newsletter.

Awaiting "abstract" for the Newsletter archive tile from Dale.

Denis
