### ISSUE TITLE
How to manage pending Blog posts at the time of CMS/Portal v2 move to prod?

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#211]
There are a few blog posts (from MapR migration) that are still in pending state in the CMS v1 (Prod / Contributions).
How do we plan to move these blog posts (in markdown) in CMS v2, so we do not lose their content, while keeping them in "Draft" so they are not published in portal v2 inadvertently?

**Comment by reddypramod85** [comment]
Postconverter script only pulls published blogs. Draft blogs in V1 need to be added manually in V2 CMS to have them in the drafts section.
