### ISSUE TITLE
Blog migration from portal V1 to portal V2 - General issues report

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#212]
Blog reviewed (Nov 2 - Feb 2021)
General issues:
 •	Almost all the MapR migrated blog posts begins with a “- - -“ underneath the “Original Post Information” section.
•	All the bullet lists are in smaller fonts than the rest of the content
•	Some or all of the code blocks/snippets are not formatted correctly. They appear as text.

**Comment by reddypramod85** [comment]
**Best Practice:** Try to put a blank line before --- and after a horizontal rule(---). The temporary fix is to add new lines before and after. For a permanent fix, I'll try to use regular expressions in the blog convertor script and update you.
**Code Snippets:** Default ``` is not getting treated as a code block. We need to mention the language. Ex: ```json or ```python etc
**Bullet List:** Yes, the font is smaller for bullets. I'm Still searching for the reason.

**Comment by choukden** [comment]
@reddypramod85 

Thank you Pramod for your research and information about possible workaround for these reported issues.
Wish the regular expression will help.
For bullet list, thank you for searching a reason and a workaround.

For code snippets, does it mean we do have to apply the workaround manually on each and every blog post that present such issue? If it is the case, where do we need to apply this manual workaround? In the blogs that have already been migrated to CMS v2? in the blogs in CMS v1? Both?

CC: @Didier-Lalli ; @drensing

**Comment by choukden** [comment]
When reviewing each and every contributor (external) blog post in CMS v1, make sure to verify:

	- line break before bullet lists
	- line break before and after the horizontal separator “---“
	- line break before a code snippet
	- programming language specified for the code snippets (```<language>)

**Comment by reddypramod85** [comment]
@choukden Can I close this issue?

**Comment by choukden** [comment]
@reddypramod85 
I guess you can close it.

Thank you !!
