### ISSUE TITLE
Update HPE Ezmeral Learn on Demand copy

### ISSUE THREAD

**Issue by reddypramod85** [hpe-dev-incubator/hpe-dev-portal#213]
Update copy to handle Academy and Learn on Demand name conflict.

![image](https://user-images.githubusercontent.com/12749370/108730918-a17a0180-74f1-11eb-9b66-3d5029456762.png)

**Comment by drensing** [comment]
Title should read: HPE Ezmeral Learn On-Demand (I just went to their website and found that they have added the hyphen between On and Demand... https://accounts.skilljar.com/accounts/signup/?next=%2Fauth%2Fendpoint%2Flogin%2Fresult%3Fnext%3D%252Fcheckout%252Fddpdmcjwxl32%26d%3D29hy38q8v9xgx&t=ddawo1d1yhfb&d=29hy38q8v9xgx )

**Comment by drensing** [comment]
Change abstract copy FROM: Curious about HPE Ezmeral Data Fabric and DevOps? Our Learn on Demand library offers introductory to advanced courses.

TO: Curious about HPE Ezmeral Data Fabric and DevOps? Learn on-demand with free technical courses.

(took mostly verbatim from their website description)

**Comment by reddypramod85** [comment]
@drensing Button name still stays the same? Go to the Academy?

**Comment by drensing** [comment]
I'm trying to figure that out... don't close this one yet

**Comment by drensing** [comment]
Apparently, these were originally referred to as courses from the MapR Academy. So there is a certain amount of "brand" associated with the use of the term Academy:

![image](https://user-images.githubusercontent.com/77496261/108883206-27ba4480-75d3-11eb-989d-b985b8ec2fab.png)

**Comment by drensing** [comment]
Based on that, I'm going to make a different recommendation for copy:
Instead of: Curious about HPE Ezmeral Data Fabric and DevOps? Learn on-demand with free technical courses.

**Use this instead:**  Learn about Data Fabric and DevOps with free on-demand technical courses found in the HPE Ezmeral learning academy. 

Keep the button as is.

**Comment by reddypramod85** [comment]
@drensing preview with updated copy

![image](https://user-images.githubusercontent.com/12749370/108904062-aa4b0000-75e3-11eb-848d-0699e0221cb6.png)

**Comment by drensing** [comment]
Can we change "learning academy" in the abstract copy to "Learning Academy"?
