### ISSUE TITLE
Copy for Newsletter Archive Page

### ISSUE THREAD

**Issue by reddypramod85** [hpe-dev-incubator/hpe-dev-portal#216]
![image](https://user-images.githubusercontent.com/12749370/108770998-9e4a3a00-7520-11eb-9b4f-fa6eed467a28.png)

**Comment by drensing** [comment]
You are looking for copy to put to the right of the email icon, correct? You can use this copy:

Each month we alert subscribers to what's new in the HPE DEV Community through our newsletter.
Find what you may have missed in any of our previous editions by visiting our archive.

**Comment by reddypramod85** [comment]
@drensing Preview with updated copy.
![image](https://user-images.githubusercontent.com/12749370/108903596-1711ca80-75e3-11eb-8e1a-70f5c1d00804.png)

**Comment by drensing** [comment]
Looks awesome. Thank you.
