### ISSUE TITLE
Portal v2 - Blogs page - The Load More option does not bring you back to where you were after reading a blog. 

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#219]
When you click Load More, then read a blog, and go back to the Blog page on Portal v2, you go back to the top of the Blog page. You do have to click "Load more" again to continue scrolling more blogs.

I believe it would be really nice to have the ability to retain the position of the "Load More" scrolling.

**Comment by reddypramod85** [comment]
@choukden Jay added the fix. Please verify it [here](https://master.d2wz01xj8bm9sl.amplifyapp.com/) and let me know if it works as expected.
