### ISSUE TITLE
Update paths/urls to be backward compatible

### ISSUE THREAD

**Issue by karatechops** [hpe-dev-incubator/hpe-dev-portal#22]
Paths should be backward compatible with the old portal. They generally follow this pattern -
`my-site.com/models` the plural of the model name is a paginated list of entries for the given model.
`my-site.com/model/post-slug` is a single entry for the given model

**Comment by IanKBovard** [comment]
Blogs with unique slug ids:

The Advent of Ephemeral Infrastructure as Code
https://developer.hpe.com/blog/Vq0ONJWvARFnkJYYY8nZ/the-advent-of-ephemeral-infrastructure-as-code

Building HPE's new design portal with headless Wordpress and Next.JS
https://developer.hpe.com/blog/VqJW05jnm5hKzXm6PqA2/building-hpes-new-design-portal-with-headless-wordpress-and-nextjs

Coffee and Critical Alerts
https://developer.hpe.com/blog/jjOEmj8omJf4GrVVV0zq/coffee-and-critical-alerts

Configuring threads for Optimal performance in HPE PowerShell Cmdlets
https://developer.hpe.com/blog/JMERRLY5R8IzgylvQ9YW/configuring-threads-for-optimal-performance-in-hpe-powershell-cmdlets

Creating a Powershell Module as a wrapper for the HPE Global Dashboard REST API
https://developer.hpe.com/blog/8nOPjXylpmC5rDBjywWZ/creating-a-powershell-module-as-a-wrapper-for-the-hpe-global-dashboard-r

HPE SimpliVity PowerShell Module
https://developer.hpe.com/blog/QljXvVoYN6IY8ErW5Qm4/hpe-simplivity-powershell-module

HPE OneSphere community contributor
https://developer.hpe.com/blog/7mDGZkRK5PcXVgwwwYXj/hpe-onesphere-community-contributor

Introducing a multi-vendor CSI driver for Kubernetes
https://developer.hpe.com/blog/n0J8kpk1DJf4y7xD2D4X/introducing-a-multi-vendor-csi-driver-for-kubernetes

**Comment by reddypramod85** [comment]
duplicate issue #92
