### ISSUE TITLE
Elipsis (...) in Featured Open Source cards on home page

### ISSUE THREAD

**Issue by drensing** [hpe-dev-incubator/hpe-dev-portal#224]
Under Chapel and SPIFFE, there is an elipsis at the end of the copy, but they are used differently. Easy fix... remove the space before the elipsis on the one under Chapel.

**Comment by reddypramod85** [comment]
@drensing We will have this issue whenever the last character has space.

**Comment by drensing** [comment]
Then why was there no issue with SPIFFE?
![image](https://user-images.githubusercontent.com/77496261/109199822-e7db9480-776d-11eb-8026-cb6792610673.png)

If the fix is to add a space after the word with SPIFFE so that any time this happens again, they all have a space before the elipsis, that's okay, too. We just need to be consistent.

**Comment by drensing** [comment]
to be more clear... to add a space after the word "standards" with the SPIFFE card
