### ISSUE TITLE
New Munch & Learn Card needs to be added to the home page

### ISSUE THREAD

**Issue by drensing** [hpe-dev-incubator/hpe-dev-portal#226]
As discussed in our V2 Portal meeting on February 19, a new card should be added for the Munch & Learn series on the home page:
![home page](https://user-images.githubusercontent.com/77496261/109176818-2fa1f200-7755-11eb-872f-f10c61c9eaf3.JPG)

Suggest copy to read:
**Munch & Learn Technology Talks**
Join our monthly community meetups to interact with experts on popular new technologies.

(Note: per Denis suggestion last week, we're changing "Technical Talks" to "Technology Talks"

**Comment by reddypramod85** [comment]
---
title: Munch & Learn Technology Talks
width: small
category: Featured Event
priority: 1
image: /img/skillup/MunchandLearn.svg
link: /campaign/munch-and-learn/
---
## Munch & Learn Technology Talks

Join our monthly community meetups to interact with experts on popular new technologies.

**Comment by reddypramod85** [comment]
@Didier-Lalli @drensing I added the M&L card on the home page and you can view the preview [here](https://deploy-preview-281--hpe-dev-portal.netlify.app/)

**Comment by drensing** [comment]
It's looking nice, Pramod. Thank you. Is there any way we could make the picture a little bigger?

**Comment by drensing** [comment]
If you could modify the copy just slightly to read "Attend our monthly community meetups where you can..." (just add the words "Attend our" to the beginning of the sentence and lower case the "m")
![image](https://user-images.githubusercontent.com/77496261/109997576-54124700-7cde-11eb-9abe-f7fa71fccde4.png)

**Comment by drensing** [comment]
This way the cards related to items like the Workshops-on-Demand, Hack Shack, and Munch & Learns all have parallel grammatical structure. Thank you.

**Comment by reddypramod85** [comment]
Made changes as requested. closing the issue.
