### ISSUE TITLE
Testing site - We don't use the correct font

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#2428]
The site: https://testing--hpe-dev-portal.netlify.app/ doesn't use the same font as https://developer.hpe.com/

**Comment by choukden** [comment]
Also, using the style below in blog post to format the bullet list to "standard" text size in the blgo posts is causing issues in blog post.

<style>
li {
   font-size: 27px;
   line-height: 33px;
   max-width: none;
}
</style>

See blog post:

https://developer.hpe.com/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-%E2%80%93-part-1-introduction-to-the-apis/

vs.

https://testing--hpe-dev-portal.netlify.app/blog/get-started-with-the-foundational-apis-for-the-hpe-greenlake-edge-to-cloud-platform-%E2%80%93-part-1-introduction-to-the-apis/
