### ISSUE TITLE
Grommet page content update

### ISSUE THREAD

**Issue by pattdepanick** [hpe-dev-incubator/hpe-dev-portal#2447]
Don't know itis a real issue but in the grommet page : 
Grommet is used by developers and designers alike to build both enterprise-class and consumer-grade applications that can be used in web, desktop, and mobile-friendly formats. It underpins many of HPE’s software-defined platforms, like [HPE OneView](https://www.hpe.com/us/en/integrated-systems/software.html), [HPE Nimble storage](https://developer.hpe.com/platform/nimble-storage/home), [HPE SimpliVity](https://www.hpe.com/us/en/integrated-systems/simplivity.html), and [HPE Composable Fabric](https://www.hpe.com/us/en/integrated-systems/composable-fabric.html).

This paragraph should perhaps be updated to list something other than old products...and mention GLP for example or more recent tools.

**Comment by Didier-Lalli** [comment]
Fixed by PR#2450
