### ISSUE TITLE
Allow external users to contribute

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#258]
We need to add a "Contribute a blog" card using:

- Icon: GitHub
- Title: Contribute
- Text:  Contribute a blog to the HPE DEV Community
- URL: /admin

**Comment by jaygiang** [comment]
@Didier-Lalli I believe this has been implemented in v2.1 with the "Be a blogger card" https://developer.hpe.com/community. If so, is it okay to close this issue?
