### ISSUE TITLE
List of blogs with image rendering issue.

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#284]
Blog: https://hpe-dev-portal.netlify.app/blog/introducing-the-hpe-gl20-iot-gateway/ 
Image at the beginning of the blog is not rendered.

Blog: https://hpe-dev-portal.netlify.app/blog/dark-mode-theming-in-grommet-how-to-set-up-and-apply-a-theme/ 
Some images are not rendered.

Blog: https://hpe-dev-portal.netlify.app/blog/open-source-elasticsearch-helped-us-globally-support-virtual-labs/ 
Some images are not rendered

Blog: https://hpe-dev-portal.netlify.app/blog/how-to-set-and-enforce-tagging-policies-in-hpe-greenlake-for-private-clo/ 
An image at the end of the blog is not rendered.

Blog: https://hpe-dev-portal.netlify.app/blog/hpe-achieves-gold-for-large-scale-enterprise-kubernetes-deployments/ 
An image is not rendered

**Comment by reddypramod85** [comment]
@choukden I fixed the image path in the mentioned blogs. Please verify and let me know.

**Comment by choukden** [comment]
@reddypramod85 
Thank you Pramod for your prompt action to fix the image issue for these blogs.
What was the issue? Why the image path was not correct on some blogs (or an image not correct while others were correct in the blog itself) while the image path was correct for most of the other blogs I reviewed manually?

**Comment by choukden** [comment]
@reddypramod85 
I checked some blogs after your last converter script run.
Community blogs looks good to me now.
Other blogs look also good. At least for the few blogs I checked today and that I manually edited over the last few days. 

Could you please delete this blog post: https://hpe-dev-portal.netlify.app/blog/introducing-a-multi-vendor-csi-driver-for-kubernetes-2/ - I have put it in Draft in CMS v1, should you run once again your converter script, it will not fetch that one.
It is a duplicate entry of https://hpe-dev-portal.netlify.app/blog/introducing-a-multi-vendor-csi-driver-for-kubernetes/) 

Thanks.

**Comment by reddypramod85** [comment]
@choukden I deleted the duplicate entry https://hpe-dev-portal.netlify.app/blog/introducing-a-multi-vendor-csi-driver-for-kubernetes-2/
