### ISSUE TITLE
Document pages that still need design

### ISSUE THREAD

**Issue by karatechops** [hpe-dev-incubator/hpe-dev-portal#32]
Add screenshots and links to pages that still need to be designed below

**Comment by IanKBovard** [comment]
/Research,
/Design,
/Support,
/opensource,
/events,
and /community, don't have designs as far as i know.
Blogs and platform pages are following old dev portal designs.

Not sure if this is intended, but the header all links to external websites

![Screen Shot 2019-11-07 at 11 31 22 AM](https://user-images.githubusercontent.com/21990914/68412639-323c9a80-0152-11ea-912e-3ba410f3c66d.png)

There isn't a direct link to the platforms list or community pages as well

New:
![Screen Shot 2019-11-07 at 11 36 51 AM](https://user-images.githubusercontent.com/21990914/68412983-eb02d980-0152-11ea-8249-211bd8fbdf3c.png)

Old:
![Screen Shot 2019-11-07 at 11 38 08 AM](https://user-images.githubusercontent.com/21990914/68413174-4f259d80-0153-11ea-9c6b-ae06c45aca75.png)

I'm assuming /platforms and /blogs need a redesign as they match the blog layout of the old portal.

old:
![Screen Shot 2019-11-08 at 8 52 19 AM](https://user-images.githubusercontent.com/21990914/68485740-691fb880-0205-11ea-8cc8-6b187c4336b7.png)

new:
![Screen Shot 2019-11-08 at 8 52 34 AM](https://user-images.githubusercontent.com/21990914/68485759-7046c680-0205-11ea-961a-9bef883fe7f7.png)
![Screen Shot 2019-11-08 at 8 52 40 AM](https://user-images.githubusercontent.com/21990914/68485762-7341b700-0205-11ea-870c-6b33f13344e4.png)

**Comment by MikeKingdom** [comment]
All true since the designs for the new portal only included the develop and main page and the main page design only had the links shown.

The header is a standard HPE header/banner and as such is expected to go to external links.

**Comment by IanKBovard** [comment]
gotcha, thanks for clarifying.
