### ISSUE TITLE
slack.hpedev.io

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#343]
I'm not sure this page was migrated, nor where it is hosted. On top of that we have received a expiry alert from letsencrypt.org about the certificate for slack.hpedev.io.

**Comment by reddypramod85** [comment]
@Didier-Lalli 

I see a DNS entry in Google domains pointing to the AWS Ec2 instance. Looks like it's a node application and i'm finding out more details and share with you soon.

Meanwhile, Can you please check the disk space of this slack ec2 instance. seems like it's full.

![image](https://user-images.githubusercontent.com/12749370/113146131-ed0c8300-91f4-11eb-9c0a-1592d687ee53.png)

![image](https://user-images.githubusercontent.com/12749370/113146185-fbf33580-91f4-11eb-9c3b-eda157695a87.png)

**Comment by reddypramod85** [comment]
From: Let's Encrypt Expiry Bot <expiry@letsencrypt.org>
Date: Tuesday, March 30, 2021 at 10:16 PM
To: HPE DEV <hpedev@hpe.com>
Subject: Let's Encrypt certificate expiration notice for domain "slack.hpedev.io"

Hello,

Your certificate (or certificates) for the names listed below will expire in 10 days (on 10 Apr 21 05:18 +0000). Please make sure to renew your certificate before then, or visitors to your web site will encounter errors.

We recommend renewing certificates automatically when they have a third of their total lifetime left. For Let's Encrypt's current 90-day certificates, that means renewing 30 days before expiration. See https://urldefense.proofpoint.com/v2/url?u=https-3A__letsencrypt.org_docs_integration-2Dguide_&d=DwICaQ&c=C5b8zRQO1miGmBeVZ2LFWg&r=CSQtyKPXyhN4hU9FAYbDNQ&m=hGRogmIqYlIvdQ4ZFgLo0NkWDJvtXfKkyLRH6MDmFOE&s=acf7_fAI6Pm2ws8th4eiuOm8FX5HVwrxDBOSlZZfhr0&e=  for details.

slack.hpedev.io

For any questions or support, please visit: https://urldefense.proofpoint.com/v2/url?u=https-3A__community.letsencrypt.org_&d=DwICaQ&c=C5b8zRQO1miGmBeVZ2LFWg&r=CSQtyKPXyhN4hU9FAYbDNQ&m=hGRogmIqYlIvdQ4ZFgLo0NkWDJvtXfKkyLRH6MDmFOE&s=E-DQE5qFkbSfGJuYNGSvA7cJTzUH227n4I-dkHVXx-w&e=  Unfortunately, we can't provide support by email.

For details about when we send these emails, please visit: https://urldefense.proofpoint.com/v2/url?u=https-3A__letsencrypt.org_docs_expiration-2Demails_&d=DwICaQ&c=C5b8zRQO1miGmBeVZ2LFWg&r=CSQtyKPXyhN4hU9FAYbDNQ&m=hGRogmIqYlIvdQ4ZFgLo0NkWDJvtXfKkyLRH6MDmFOE&s=fBcAslLynHgsT1oCrbTm9lDMoErET3MhUIga7dt8PjE&e=  In particular, note that this reminder email is still sent if you've obtained a slightly different certificate by adding or removing names. If you've replaced this certificate with a newer one that covers more or fewer names than the list above, you may be able to ignore this message.

If you are receiving this email in error, unsubscribe at:
  https://urldefense.proofpoint.com/v2/url?u=http-3A__delivery.letsencrypt.org_track_unsub.php-3Fu-3D30850198-26id-3D52977f7d7a8f4a9493b7ada8b72c1e76.cjP6VCvGu56x0VhUfMdnucw4jjQ-253D-26r-3Dhttps-253A-252F-252Fmandrillapp.com-252Funsub-253Fmd-5Femail-253Dh-25252A-25252A-25252A-25252A-252540h-25252A-25252A-25252A-25252A.-25252A-25252A-25252A&d=DwICaQ&c=C5b8zRQO1miGmBeVZ2LFWg&r=CSQtyKPXyhN4hU9FAYbDNQ&m=hGRogmIqYlIvdQ4ZFgLo0NkWDJvtXfKkyLRH6MDmFOE&s=dauTkFAPmsgPxGoLzUKc9-6UnA8cI_qKGNkD9SFHjiA&e= 
Please note that this would also unsubscribe you from other Let's Encrypt service notices, including expiration reminders for any other certificates.

Regards,
The Let's Encrypt Team

**Comment by reddypramod85** [comment]
I and Fred worked on this to renew the certificate.
