### ISSUE TITLE
How to define rewrite rule for blogs in CMS v2?

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#346]
@reddypramod85 
Hi Pramod

To satisfy Michael's Mattsson request, I had to create a "rewrite" rule in CMS v1 for the blog post below.

The URL: https://developer.hpe.com/blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri is rewritten into https://developer.hpe.com/blog/introducing-an-nfs-server-provisioner-for-the-hpe-csi-driver-for-kuberne 

How do we create a similar rewrite rule in CMS v2?

I would like to have the same "rewrite" operation for this blog post so, after Move to prod of portal v2, when a user clicks a hotlink for the blog URL https://developer.hpe.com/blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri the URL is actually re-written into https://developer.hpe.com/blog/introducing-an-nfs-server-provisioner-for-the-hpe-csi-driver-for-kuberne 

Thanks
Denis

CC: @jaygiang

**Comment by reddypramod85** [comment]
@choukden 
Navigate to [AWS Amplify](https://console.aws.amazon.com/amplify/home?region=us-east-1#/d2wz01xj8bm9sl)

Click on Rewrites and Redirects on left side bar -> click on edit -> scroll to bottom -> click on Add rule -> make an entry -> save.

![image](https://user-images.githubusercontent.com/12749370/113145674-5213a900-91f4-11eb-8ec7-2c0b79da2702.png)

CC: @jaygiang

**Comment by choukden** [comment]
@reddypramod85 
CC: @jaygiang 

Hi pramod, I have create a "rewrite" action for this

Source address: /blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri

Target address: /blog/introducing-an-nfs-server-provisioner-for-the-hpe-csi-driver-for-kuberne

Operation: rewrite

How do I activate the rule once it is defined in AWS amplify?

I have tested to access  https://hpe-dev-portal.netlify.app/blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri 
from the browser, and the rewrite does not seem to be effective. I get error404.

Denis

**Comment by jaygiang** [comment]
CC: @reddypramod85 

Hi @choukden 

Using the amplify host name [https://master.d2wz01xj8bm9sl.amplifyapp.com/](https://master.d2wz01xj8bm9sl.amplifyapp.com/) with the path name should work. 

[https://master.d2wz01xj8bm9sl.amplifyapp.com/blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri](https://master.d2wz01xj8bm9sl.amplifyapp.com/blog/xABwJY56qEfNGMEo1lDj/introducing-a-nfs-server-provisioner-and-pod-monitor-for-the-hpe-csi-dri)
