### ISSUE TITLE
Missing image in SimpliVity pages

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#375]
I'm trying to update the SimpliVity according to what Anne asked. But I have this picture present on all subpage (upper left corner) which is missing.

https://deploy-preview-298--hpe-dev-portal.netlify.app/platform/hpe-simplivity/home/

**Comment by reddypramod85** [comment]
@Didier-Lalli I provided a fix, can you please verify? https://deploy-preview-298--hpe-dev-portal.netlify.app/platform/hpe-simplivity/home/

**Comment by Didier-Lalli** [comment]
That's perfect. Can I merge my PR then?

**Comment by reddypramod85** [comment]
@Didier-Lalli Yes, I can merge it for you.
