### ISSUE TITLE
Verify Netlify-CMS works with current MVP build

### ISSUE THREAD

**Issue by karatechops** [hpe-dev-incubator/hpe-dev-portal#39]
- [ ] Fix platform pages
- [x] Make sure all the stuff works

**Comment by IanKBovard** [comment]
It looks like the netlify cms doesn't currently support nested collections such as content/platforms/simplivity/home.md. A temporary solution would be to make a collection for each folder, while we wait for netlify cms to support this. Which, by the looks of it, should be soon.

https://github.com/netlify/netlify-cms/issues/513

**Comment by IanKBovard** [comment]
https://github.com/netlify/netlify-cms/pull/2897
