### ISSUE TITLE
Error 404 on https://developer.hpe.com/signup/

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#418]
![image](https://user-images.githubusercontent.com/11722750/116046986-e3e7c800-a673-11eb-8743-e6a25bff2c18.png)

Linked from the Hack Shack

**Comment by Didier-Lalli** [comment]
We might want to create a redirect from: https://developer.hpe.com/signup/
to https://developer.hpe.com/newsletter-signup/

**Comment by reddypramod85** [comment]
Added the redirect link in AWS Amplify but the join community card will be removed from the Hack Shack community section as we no longer have it in V2.
