### ISSUE TITLE
PR#404 has a conflict that must be resolved before continuing.

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#426]
Patrick added "Fredo" picture to the blog posts authored by Frederic.
Among these blog posts, there is one issue in the pull request (#404)
Update Blog “2021-04-12-from-jupyter-notebooks-as-a-service-to-hpe-dev-workshops-on-demand” #404
PR #404  has a conflict that must be resolved before continuing.

Could you please assist?

Thanks
Denis

**Comment by choukden** [comment]
@reddypramod85, @jaygiang 
The problem seems to be solved. Did you make anything to fix the problem?
Denis.

**Comment by reddypramod85** [comment]
@choukden I'll get in touch with Patrick to update Fredo's picture.

**Comment by choukden** [comment]
@reddypramod85 
thank you so much.
does it mean the root cause of the issue was the picture of the author?
was the image for this blog different than the author image of the other blogs written by Fredo?

CC: @patrickfrancoisp ;

**Comment by reddypramod85** [comment]
@choukden 

Merge conflict occurs when 2 people modify the same file. So, the issue was not related to the picture, it's related to other code changes added after creating this PR and later tried to merge these changes to the master branch.
