### ISSUE TITLE
Pull Requests #442 and #434 from Contributors are queued - waiting to run tis check for AWS Amplify.

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#443]
@reddypramod85 , @jaygiang 
We have got two new contributions (PR #442 and PR #434 ) submitted through the CMS.

The Netlify has been processed successfully. However, the process is queued for AWS Amplify. 
Could you please investigate to better understand what could be the root cause of the issue, and how to workaround it, shoudl it happen again?

I suspect the contributors have made several back & forth between "Drafts" and "In Review" in the CMS Workflow editor.
And maybe, this is something AWS amplify does not support/like. 

Thanks
Denis

**Comment by choukden** [comment]
AWS Amplify issue is not consistent, only few times it’s failing to preview the PR and I don’t think it won’t block us. I see people are facing this issue and reported it.

https://github.com/aws-amplify/amplify-console/issues/367 

I’ll keep checking the PR often and try to rebuild the PR if it’s queued.

Thanks,
Pramod

**Comment by reddypramod85** [comment]
There is an issue logged in the AWS Amplify GitHub repo and it's still open.

![image](https://user-images.githubusercontent.com/12749370/119660092-78b91f00-bdf4-11eb-98a3-ca2d67c07ff1.png)
