### ISSUE TITLE
When using CMS v2 we are getting error The backend service is experiencing an outage.

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#446]
Hi @reddypramod85, @jaygiang 

Today, we discussed with Dale and Didier the best approach to go through "Community" blog post editorial review.
While we were testing a few ways of doing review, I connected to CMS v2 and I get message "_The Backend service is experiencing an outage. See https://www.githubstatus.com for more information._"
A refresh of the browser cleared the message for a few minutes, then the pop up message appeared again.

later, Dale experienced the same issue when editing her blog post in CMS v2.

Could you please look at this issue?

Thanks
Denis

**Comment by reddypramod85** [comment]
@choukden I don't see any issue now. Maybe it's because of GitHub maintenance. https://www.githubstatus.com 

Let me know if you still experience the issue.

**Comment by reddypramod85** [comment]
@choukden I did receive this error when I tried to delete the test blog from CMS. Let's wait till the GitHub maintenance is finished to verify the issue again.

**Comment by reddypramod85** [comment]
@Didier-Lalli @choukden I don't think we have the issue after the GitHub Maintenance.
