### ISSUE TITLE
Open Authoring is not working as expected

### ISSUE THREAD

**Issue by reddypramod85** [hpe-dev-incubator/hpe-dev-portal#477]
![image](https://user-images.githubusercontent.com/12749370/117981489-ada87a80-b2fa-11eb-9ba1-9975286ff80e.png)

**Comment by Didier-Lalli** [comment]
Folks like Shanice have issues on the CMS of a forked repo. And it's really hard to help them. We also have issues working with the main repo. We cannot get to the Workflow section, which makes it impossible for an author to find a blog in draft. That's a real pain.

**Comment by reddypramod85** [comment]
@Didier-Lalli 

# Changes Made
Looks like the workflow tab is working now. I'm not sure which change made it work but maybe it's because of closing a PR. I did a couple of things.
- I created a new Client ID and Secret for GitHub authentication in GitHub and added it to Netlify. You will see "Authorize reddypramod85" from now on instead of "Authorize Mike Kingdom".
- Closed and merged a few pending PR's. As the workflow tab was complaining about the "fork" I thought the issue might have been related to a PR. It worked :)

**Comment by Didier-Lalli** [comment]
Ok. Thanks. Is it not possible to use a more generic name. If you need a github account, we have the HPEDevCom

**Comment by reddypramod85** [comment]
@Didier-Lalli Yes, I can use it. Please do share the details. I will update.
