### ISSUE TITLE
Two Pull Requests #500 and #501 with a single check :AWS amplify instead of 2 checks - Netlify and Amplify? 

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#504]
Hi @reddypramod85 , @jaygiang 

Michael Mattsson submitted two new blog posts through the CMS editor.
-	https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/501 
-	https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/500

Would you know why there is only one check (AWS Amplify) instead of two checks (Netlify and AWS Amplify)?

Best regards
Denis

**Comment by Didier-Lalli** [comment]
In my opinion, this is due to the fact that these PR are not tagged with any netlifycms label like the other are. Seem like this doesn't trigger the Netlify CMS builds while working fine with Amplify.

**Comment by choukden** [comment]
Looks like something changed recently in the check process. One of the side effects  is that the status flag “View Preview” and the “Check for Preview” are no longer available in CMS editor (Netlify). This breaking the guidelines we documented in the CMS v2 editor guide for external contributors.
