### ISSUE TITLE
Unable to update existing blog post Discover Dont Miss it - CMS is showing error "Failed to persist entry: API_ERROR: Reference update failed.

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#524]
Hi Jay, @jaygiang 

Dale and I are experiencing an issue when trying to update the blog post https://developer.hpe.com/blog/hpe-discover-2021-don%E2%80%99t-miss-these-hpe-dev-industry-expert-talks-and-hands-on-workshops/ through the CMS v2 editor.

We get error below for this particular blog post entry when trying to "Save changed": 
Failed to persist entry: API_ERROR: Reference update failed.

Could you please look at the reason for this issue? is there a conflict anywhere? Is it possible something to do with the fact it is a Featured blog in the home Panels? 

Thanks
Denis

**Comment by reddypramod85** [comment]
@choukden We need to delete the branch as soon as we merge it into the master to avoid these errors. I just did a clean-up of existing branches to fix this error and I'm able to edit the blog now.

**Comment by jaygiang** [comment]
@choukden, it looks like this issue has been resolved. I will close this issue.
