### ISSUE TITLE
New community blog post submission - All check have failed 

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#532]
Hi Jay, Pramod

Francois Donze has submitted a new blog post via the community CMS editor. This morning, the check was successful. I believe Francois made some adjustment further to the technical feedback provided by Frederic. I do see the last check failed.

https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/527

Could you please assist?

Denis

@jaygiang ; @reddypramod85

**Comment by reddypramod85** [comment]
@choukden I redeployed the build and it was successful. Can you please ask Francois Donze to make any minor changes and push the commit again to test the same?

**Comment by choukden** [comment]
Dale is going to go through the editorial review and she will certainly provide Francois with additional suggestions for edits. So Francois will edits his blog posts and submit changes. 
In the meantime, I will check with Francois if he could make a minor changes in his CMS editor and see how the check goes.

**Comment by choukden** [comment]
@reddypramod85 
I understood this issue was due to an AWS amplify outage.
How do we check if there was an outage on Amplify?

**Comment by jaygiang** [comment]
Hi @choukden,

I'm not sure if Pramod has answered this already, but from what I remember, I think he was able to get an update from looking at the AWS Amplify issues https://github.com/aws-amplify/amplify-js/issues. 

Also, I found [this ](https://status.aws.amazon.com/), which can possibly let us know if Amplify is out.

**Comment by choukden** [comment]
@jaygiang I think you can close this issue.
Thanks
Denis
