### ISSUE TITLE
Lists does not render with the same fonts as paragraphs

### ISSUE THREAD

**Issue by datamattsson** [hpe-dev-incubator/hpe-dev-portal#539]
Example: https://developer.hpe.com/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes/#summary

**Comment by choukden** [comment]
Hi Michael (@datamattsson)

We also noticed the same.

A workaround is to go into "Markdown" mode, and insert a line break between each list item, as well as a line break after the standard paragraph and the first item of the list. This would need to be done whenever you edit/update your a blog post.

I documented this workaround in the CMS guide in the Tips & tricks section [here.](https://github.com/hpe-dev-incubator/hpe-dev-portal/blob/master/docs/ContributorGuide-v2.md#tips-and-trick-using-the-cms-editor).

**Comment by jaygiang** [comment]
Thanks @choukden for providing the documentation. 

I went ahead and added those line breaks https://deploy-preview-700--hpe-dev-portal.netlify.app/blog/host-based-volume-encryption-with-hpe-csi-driver-for-kubernetes/#summary. 

@datamattsson @choukden If everything looks good, I'll go ahead and push this live.

**Comment by choukden** [comment]
@jaygiang 
Thank you Jay. This looks good to me. The change can be merged and the issue closed.
Thanks
Denis
