### ISSUE TITLE
Button styles differ - Newsletter Sign-up button color is not consistent with the Try Now! button in Platform pages for Workshops-on-demand.

### ISSUE THREAD

**Issue by datamattsson** [hpe-dev-incubator/hpe-dev-portal#544]
The button "Try Now!" does not match "Subscribe Now". How can we use a coherent button style?

- https://developer.hpe.com/platform/hpe-nimble-storage/home/

**Comment by choukden** [comment]
@Didier-Lalli, @reddypramod85 

This is a good suggestion. 

Thsi is the HTML code we currently have in the platform pages 

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<div class="w3-container w3-center w3-margin-bottom">
  <a href="https://hackshack.hpedev.io/workshops"><button type="button" class="w3-btn w3-teal">Try now!</button></a>
</div>

From the w3.css (https://www.w3schools.com/w3css/w3css_colors.asp) I have tried with class="w3-btn w3-green" but I still cannot get the same color as the Subscribe Now button for the Newsletter.
Also, the "Try now!" is in white. What is the HTML syntax to make the text in black?

Denis

**Comment by Didier-Lalli** [comment]
I could not get this to work myself. Jay fixed it for me for the Try Now!

**Comment by choukden** [comment]
Didier suggested to have the Subscribe Now button color and text aligned with the "try now" button of the WOD button in Platform pages.

**Comment by datamattsson** [comment]
I would prefer the "Subscribe Now" button as the design we'd go with. It goes better with the overall design.

**Comment by jaygiang** [comment]
@datamattsson @choukden I've updated the **Try Now!** button style to match the **Subscribe Now** button. The **Subscribe Now** button is a Grommet component, so I think it would be best to go with this style. 

https://deploy-preview-697--hpe-dev-portal.netlify.app/platform/hpe-nimble-storage/home/

If this looks good to you, I can make this same update to the other platform **Try Now!** buttons.

**Comment by choukden** [comment]
@jaygiang , @datamattsson 
Thank you very much Jay for this change. I like the "Try Now!" button design. It is consistent with the other button throughout the Dev portal. If everyone agrees, I would go for it on every occurrence of "Try Now!" button in other platform pages.

Thanks again!



CC: @Didier-Lalli

**Comment by datamattsson** [comment]
LGTM
