### ISSUE TITLE
Error when navigating CMS Workflow as admin - Editorial_workflow_error: content is not under editorial workflow 

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#547]
Hi Pramod, Jay

I am not sure how to figure out what PR (or branch) is conflicting and causing the issue I am facing right now when navigating to the Workflow:

_Failed to load entry:_ 
_EDITORIAL_WORKFLOW_ERROR:content is not under editorial workflow._

It worked well until I approved (Merge) the PR #541. I deleted the associated branch. 
I notice there are new PR #545 & PR #546. Maybe one of it is causing the issue when navigating to the Workflow section of the CMS editor.

**Comment by choukden** [comment]
Looks like that adding a label netlify-cms/pending_review to a PR is causing this type of issue in the Workflow editor. 

I think the issue can be closed.

**Comment by reddypramod85** [comment]
@choukden Yes, you can close this issue if you don't see the error.
