### ISSUE TITLE
Implement a Use Cases drop down menu

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#571]
![image](https://user-images.githubusercontent.com/11722750/123817039-1a51f580-d8f8-11eb-831c-c6bfa290e788.png)

And focus on 3 use cases such as:

- I want to manage my infrastructure as code
- I want to manage Kubernetes
- I need to manage large data sets

Then team up with SME of each discipline to build each landing page. These page should present things we have provide that relates to the use case (workshops, M&L, Blogs, slack, ...), plus other references.

**Comment by drensing** [comment]
Equally important to the Persona "value proposition" enhancement. Helping those who come in who have a particular problem they need to solve immediately be able to recognize it in our drop down menu and then being able to see how HPE solves the issue.
