### ISSUE TITLE
Fold the Open source page under the Community as an separate card

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#573]
Open source page is not not maintained, not providing what we expected. A card in community page would be largely enough.

**Comment by drensing** [comment]
Agreed that it should be placed somewhere else. Not sure Community page is the right place. Or maybe it should be in at least two places. I would make sure it was somehow linked from the Platform page as well.  We might also consider sprinkling it throughout the site, like we do with the Newsletter (or additionally doing so). It is very important that HPE is seen as playing in this area (in spite of our constant lack of focus on keeping an updated open source website).
