### ISSUE TITLE
Add opt-in for newsletter in WoD registration

### ISSUE THREAD

**Issue by jaygiang** [hpe-dev-incubator/hpe-dev-portal#584]

**Comment by Didier-Lalli** [comment]
I'm not sure I understand this. We should have them opt-in for being contacted as workshop-on-demand users. First. Then maybe another one to force them to subscribe to the newsletter.

**Comment by drensing** [comment]
Didier has created an Opt-In/Opt-Out page that we've added a link to from the Newsletter itself. The idea is to create one page that the Newsletter can point to, the Workshops on Demand can point to, and the Munch & Learns can point to. I think this will get us to where we need to be. Needs to be reviewed by Rebecca to see if we need to make any modifications, but definitely getting us there. In addition, if we're thinking here that adding an opt-in for the newsletter in WoD registration will help us better count how many community members, I don't think we should be relying on just newsletter subscribers as our only community members. We need to count all the folks who take our WoD and M&L's as well, and we do so in SendGrid. So, I don't know if this is actually necessary.

**Comment by jaygiang** [comment]
So I think this issue is actually suppose to be what @Didier-Lalli mentioned:
> We should have them opt-in for being contacted as workshop-on-demand users. 

and he made an issue for it here in the Hack Shack Github repo [Add attendees email in SendGrid lists](https://github.com/HewlettPackard/HackShack-Session-Landing-Page/issues/202)

Since @drensing mentioned that the Opt-In/Opt-Out page that Didier created is getting us where we need to be, I think I can close this issue. Dale, I believe this is the page you're referring to? 
<img width="300" alt="Screen Shot 2021-07-02 at 9 07 11 AM" src="https://user-images.githubusercontent.com/11492092/124303018-c96c1800-db16-11eb-98ec-bf9e2bbfe104.png">

**Comment by drensing** [comment]
Yes, but until the group understands this fully, not sure we should close it just yet.
