### ISSUE TITLE
Newsletter signup submit button doesn't look like a button

### ISSUE THREAD

**Issue by MikeKingdom** [hpe-dev-incubator/hpe-dev-portal#59]
Currently the Submit button on the newsletter signup page just looks like text

**Comment by reddypramod85** [comment]
@MikeKingdom I see it as a button. Can you please provide more information on the issue?

![image](https://user-images.githubusercontent.com/12749370/109178300-54df3200-774e-11eb-8f63-c78df579b7f1.png)
