### ISSUE TITLE
Image uploaded in CMS - admin or external contributor - are not saved in expected GitHub repo /static/img

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#598]
Hi Jay (@jaygiang)

as per our discussion today, using his forked copy of the CMS as external contributor, Ben Robbins has created a new platform "SmartSim" today and I have published it in DEv portal. 

Later, he wanted to add a diagram about the SmartSim Architecture. Although we can see the image in the right side of the CMS editor while editing the "Platform", the image is not rendered in the published version of the SmartSim platform.
The image seems to be stored locally somewhere, but not in GitHub /static/img path.

Could you please check what might be wrong?

Thanks
Denis

**Comment by jaygiang** [comment]
Hi @choukden 

The image is now being stored in the correct path and is now rendered in production: https://developer.hpe.com/platform/smartsim/home/

Also, I made an update where if the content owner uploads a platform logo/image in the CMS, it will now be saved in the repo path `/static/img/platforms`. 
<img width="984" alt="Screen Shot 2021-07-07 at 11 20 29 AM" src="https://user-images.githubusercontent.com/11492092/124810082-bf328b00-df15-11eb-884e-acf866f44eb0.png">

**Comment by choukden** [comment]
Ok @jaygiang 
So going forward, when creating a new platform, the Image logo image for the platform will be stored in Github repo path /static/img/platforms. And any other images uploaded in the Body of the platform page will be saved in the repo path /static/img. 

Correct?

**Comment by jaygiang** [comment]
@choukden Yes, that is correct 👍
