### ISSUE TITLE
Nav on top and bottom doesn't wrap on smaller screens like mobile

### ISSUE THREAD

**Issue by MikeKingdom** [hpe-dev-incubator/hpe-dev-portal#60]
The top and bottom navs now have more items and no longer fit on smaller screens like mobile in portrait mode.

![image](https://user-images.githubusercontent.com/12054362/73092437-dbfe0e80-3e99-11ea-876c-6e777f1bc82c.png)

![image](https://user-images.githubusercontent.com/12054362/73092468-eddfb180-3e99-11ea-83cb-cdfed6c57ddf.png)

**Comment by reddypramod85** [comment]
Need to rework the header view on mobile. Something like a hamburger icon instead of the list.
![image](https://user-images.githubusercontent.com/12749370/109178049-10ec2d00-774e-11eb-83d0-1de70e6c5ccb.png)

**Comment by reddypramod85** [comment]
Eric provided the fix for the mobile screen.

![image](https://user-images.githubusercontent.com/12749370/109708672-513e1780-7b61-11eb-8581-b33d466fbdff.png)
