### ISSUE TITLE
PR #591 is queued for AWS Amplify check process

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#622]
@jaygiang 

PR #591 

The check for the PR above is queued for AWS amplify.
NetLify check completed successfully. 
I would like to publish the blog post.  Do you know if I can Merge the Pull Request or is there anything to do on AWS amplify side before merging the PR (i.e.: rebuild the PR in AWS amplify**)?

I remember experiencing similar issue and reporting the issue to Pramod. But I am not sure how the problem was actually fixed by Pramod.  
Reference: https://github.com/aws-amplify/amplify-console/issues/367 

Thanks

Denis

**Comment by jaygiang** [comment]
@choukden 

Thanks for providing the reference to the amplify-console issue. I also found another reference talking about the same [issue](https://github.com/aws-amplify/amplify-console/issues/550). Pramod left a comment a while back and it seems like there still is no fix for this yet. 

From looking through the reference, it looks like either two of these scenarios happened to PR #591: 

> 1. Open a PR against a non-master branch, then switch the base branch of the PR to master branch.
> 2. Have a PR that was opened against master branch, with previews working. While a build is in progress, push a new commit to the PR branch.

If I go the aws-amplify console, it looks like the preview has been fully built and deployed
<img width="1823" alt="Screen Shot 2021-07-21 at 9 59 06 AM" src="https://user-images.githubusercontent.com/11492092/126528967-daf42413-e45d-49c9-9359-34e5d7b9b45d.png">
and the aws-amplify preview for this PR shows the created blog https://pr-591.d2wz01xj8bm9sl.amplifyapp.com/

From looking at how Pramod proceeded with a previous PR with the same issue PR #442, if you click on **View Details**, he went ahead and merged  the PR without **AWS Amplify Console Web Preview** check being passed. So with this, I believe that as long as the aws-amplify preview is showing that it's fully built and deployed in the console, then we should be good to merge. Can you check that everything in the preview https://pr-591.d2wz01xj8bm9sl.amplifyapp.com/ looks up to date before merging?

**Comment by choukden** [comment]
@jaygiang 
Thank you so much for looking into this.

I compared the preview from AWS Amplify and the Netlify Preview, and both preview look the same and they are up to date with latest update from the author of the post.

In AWS amplify, the build #16 associated with the PR terminated with success. So this is really the AWS Amplify check process that did not return the completed result to GitHub as described in the issue here: https://github.com/aws-amplify/amplify-console/issues/367 

I will give it a try to the merge of the PR.

Denis

**Comment by jaygiang** [comment]
@choukden 

Ahhh I see. Awesome! It looks like the new blog is showing up in production 👍 

Thanks!

**Comment by choukden** [comment]
@jaygiang 

PR #591 merged successfully: 
Blog post published- URL is here: https://developer.hpe.com/blog/accessing-dtap-in-pods/ 

You may want to close this issue.

Thanks again for your help.
Denis
