### ISSUE TITLE
Reverse sort order of Munch and Learn so that most recent shows up first

### ISSUE THREAD

**Issue by jaygiang** [hpe-dev-incubator/hpe-dev-portal#634]
- Sort Munch and Learn so that the most recent shows up on top
![image001](https://user-images.githubusercontent.com/11492092/127208189-803d4590-4422-4f16-99bb-1c4a28ba50bf.png)

**Comment by choukden** [comment]
The page is managed in the CMS editor. I would like to discuss with Didier as he is the owner/creator of the page before editing it to reverse sort order.

**Comment by Didier-Lalli** [comment]
Fixed by PR#643
