### ISSUE TITLE
Add "Related Events" to platform pages

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#699]
The same way we have "Related Blogs", showing a "Related Events" section (if not empty) will be a nice feature (idea from Heather Leopard). I noticed that events can have tags, even though we don't use it at the moment.

**Comment by jaygiang** [comment]
@Didier-Lalli 

For testing purposes, I used the Spiffe-and-Spire platform page and added munch-&-learn and Discover 2021 events as **Related Events**. Adding a platform tag in the event markdown should now show as **Related Events**. 

https://deploy-preview-839--hpe-dev-portal.netlify.app/platform/spiffe-and-spire-projects/home/

**Comment by jaygiang** [comment]
This enhancement has been implemented: https://github.com/hpe-dev-incubator/hpe-dev-portal/pull/839
