### ISSUE TITLE
Renaming a Platform Page does not change its URL

### ISSUE THREAD

**Issue by choukden** [hpe-dev-incubator/hpe-dev-portal#721]
Hi Jay, @jaygiang 

I need your help here to figure out the options to align the URL with the Platform page name when one renames the platform page title.

For example, Ron Dharma is currently working on developing the "Platform" page for Data Services Cloud Console #687 
The original name of the platform page was "Data Service Cloud Console API", which translated to the preview URL as "/platform/data-services-cloud-console-api/home/"
Notice the "data-services-cloud-console-api" in the URL.

Later, he changed the platform title to "Data Services Cloud Console". However, if you look at the URL of the page (Preview), you will still see the "data-services-cloud-console-api" in the URL.

This could become a problem later to tie future blog posts to the DSCC platform page. We will have to use the tag "data-services-cloud-console-api" tag instead of the data-services-cloud-console tag.

Is there a programmatic way to change the URL of the platform page (before or after it is published) to align the URL with its actual Platform page title?
or is the only option to ask Ron to create a new Platform page entry with the exact same content as the one that is currently developing in its forked copy of the CMS, and delete the 'old' entry from the CMS editor?

CC: @Didier-Lalli

**Comment by jaygiang** [comment]
Hi @choukden, 

Yes, I can update the URL to "Data Services Cloud Console" after it's been published.

Please let me know when it gets published.

**Comment by choukden** [comment]
Hi @jaygiang 

This is cool. I will let you know when we have the "go" to publish the DSCC platform page. We are waiting for Ron Dharma to give us the green light for the platform publication.

BTW, Could your magic trick be applied for the change of the title of "HPE Ezmeral Runtime" to "HPE Ezmeral Runtime Enterprise" ? I mean do we need to create a new platform page "HPE Ezmeral Runtime Enterprise" and then phase out the platform page "HPE Ezmeral Runtime" ? or could we simply change the title of the existing HPE Ezmeral Runtime platform page and get the URL updated from /platform/hpe-ezmeral-runtime/home/ into /platform/hpe-ezmeral-runtime-enterprise/home ? if the latter, the process for renaming a platform page would be somewhat simplified going forward.

**Comment by jaygiang** [comment]
Hi @choukden, 

Yes the latter is possible. I'll just be manually changing the URL name to `/platform/hpe-ezmeral-runtime-enterprise/home` after you have made changes and published.

**Comment by choukden** [comment]
Hi Jay, @jaygiang 

Just to let you know I have published the DSCC platform page.
https://developer.hpe.com/platform/data-services-cloud-console-api/home/

Please go ahead with the change of the platform page URL to be https://developer.hpe.com/platform/data-services-cloud-console/home/

Thanks,
Denis
