### ISSUE TITLE
Add a Get Started button on Be a blogger page

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#724]
Add a fourth bullet:

- Connect to our Content Management System to fork our repo and start working on your blog

Add a Get Started button which links to /admin so they can start the process.

**Comment by jaygiang** [comment]
@Didier-Lalli Were you looking for something like this? https://deploy-preview-837--hpe-dev-portal.netlify.app/contribute

Or did you want to add a button below the 4th bullet point that says "Get Started"?

**Comment by salvador001** [comment]
please assign this to me 
it would be great
