### ISSUE TITLE
Change link to our open source page in place of the HPE one

### ISSUE THREAD

**Issue by Didier-Lalli** [hpe-dev-incubator/hpe-dev-portal#737]
Can we update the target ot the arrow in the far right to get to our open source page in place of the opensource@hpe.

![image](https://user-images.githubusercontent.com/11722750/134695289-53e51d95-0dcd-4eea-a6d3-6a1d26ced7c5.png)

**Comment by jaygiang** [comment]
@Didier-Lalli the arrow should now take the user to our Open Source page.
